// Builds css/<page>.css (Tailwind, using each page's own theme in tailwind/<page>.config.cjs) and the local fonts.
// Run:  npm install && npm run build      (only needed after changing a page's markup, script classes or theme)
import { execFileSync } from 'node:child_process';
import { copyFileSync, mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = dirname(fileURLToPath(import.meta.url));
const pages = ['signin', 'creds', 'maindash', 'analysing', 'result'];
mkdirSync(resolve(root, 'css'), { recursive: true });
mkdirSync(resolve(root, 'fonts'), { recursive: true });

for (const page of pages) {
  execFileSync('npx', ['tailwindcss', '-c', `tailwind/${page}.config.cjs`, '-i', 'tailwind/base.css', '-o', `css/${page}.css`, '--minify'],
    { cwd: root, stdio: 'inherit' });
}

// Fonts: bundled, so the pages work without internet access.
const fonts = [
  ['node_modules/@fontsource-variable/inter/files/inter-latin-wght-normal.woff2', 'inter-latin-wght-normal.woff2'],
  ['node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-400-normal.woff2', 'jetbrains-mono-latin-400-normal.woff2'],
  ['node_modules/@fontsource/jetbrains-mono/files/jetbrains-mono-latin-500-normal.woff2', 'jetbrains-mono-latin-500-normal.woff2'],
];
for (const [from, to] of fonts) {
  if (!existsSync(resolve(root, from))) throw new Error(`Missing ${from}; run npm install first`);
  copyFileSync(resolve(root, from), resolve(root, 'fonts', to));
}
writeFileSync(resolve(root, 'css/fonts.css'), `/* generated by build.mjs */
@font-face { font-family: 'Inter'; font-style: normal; font-display: swap; font-weight: 100 900; src: url('../fonts/inter-latin-wght-normal.woff2') format('woff2'); }
@font-face { font-family: 'JetBrains Mono'; font-style: normal; font-display: swap; font-weight: 400; src: url('../fonts/jetbrains-mono-latin-400-normal.woff2') format('woff2'); }
@font-face { font-family: 'JetBrains Mono'; font-style: normal; font-display: swap; font-weight: 500; src: url('../fonts/jetbrains-mono-latin-500-normal.woff2') format('woff2'); }
`);
console.log('Built css/ and fonts/');
