"""Verification of issuer-signed QR tokens (Ed25519).

Token = base64url(payload JSON) + "." + base64url(signature). The signature is checked over the exact
payload bytes that were scanned, so there is no canonicalisation step an attacker could exploit.

Payload: {"v": 1, "iss": "<issuer_id>", "kid": "<key id>", "t": "<document type id>",
          "f": {<schema field name>: <value>, ...}}

The issuer signs with a private key that never leaves issuer_service/. Pramanik holds only the public
keys, in config/issuer_keys.json (generated by issuer_service/setup_keys.py; override with ISSUER_KEYS_FILE).
A key marked "retired" still verifies certificates issued under it; "revoked" does not.
"""
import base64
import binascii
import json
import os
from pathlib import Path
from typing import Any, Optional

from cryptography.exceptions import InvalidSignature
from cryptography.hazmat.primitives.asymmetric import ed25519

from .. import config

# Reason codes (each has an officer-facing text, "qr_sig_<code>", in config/ui.json)
MALFORMED, UNKNOWN_KEY, KEY_REVOKED, BAD_SIGNATURE, NO_KEYS = (
    "malformed", "unknown_key", "key_revoked", "bad_signature", "no_keys")


def b64url_decode(s: str) -> bytes:
    return base64.urlsafe_b64decode(s + "=" * (-len(s) % 4))


def b64url_encode(b: bytes) -> str:
    return base64.urlsafe_b64encode(b).decode("ascii").rstrip("=")


def keys_path() -> Path:
    return Path(os.environ.get("ISSUER_KEYS_FILE", config.BACKEND_DIR / "config" / "issuer_keys.json"))


def load_keys() -> list[dict]:
    try:
        return json.loads(keys_path().read_text(encoding="utf-8")).get("keys", [])
    except (OSError, ValueError):
        return []


def verify_token(token: str) -> tuple[bool, Optional[dict[str, Any]], str]:
    """Returns (valid, payload, reason_code). reason_code is "" when valid."""
    parts = (token or "").split(".")
    if len(parts) != 2 or not all(parts):
        return False, None, MALFORMED
    try:
        payload_bytes, sig = b64url_decode(parts[0]), b64url_decode(parts[1])
        payload = json.loads(payload_bytes.decode("utf-8"))
    except (ValueError, binascii.Error, UnicodeDecodeError):
        return False, None, MALFORMED
    if not isinstance(payload, dict) or not isinstance(payload.get("f"), dict):
        return False, None, MALFORMED
    kid, iss = payload.get("kid"), payload.get("iss")
    if not kid or not iss:
        return False, None, MALFORMED

    keys = load_keys()
    if not keys:
        return False, None, NO_KEYS
    entry = next((k for k in keys if k.get("kid") == kid and k.get("issuer_id") == iss), None)
    if entry is None:
        return False, None, UNKNOWN_KEY
    if entry.get("status") == "revoked":
        return False, None, KEY_REVOKED
    try:
        ed25519.Ed25519PublicKey.from_public_bytes(bytes.fromhex(entry["public_key"])).verify(sig, payload_bytes)
    except (InvalidSignature, ValueError, KeyError):
        return False, None, BAD_SIGNATURE
    return True, payload, ""
